09/12/2015 12:43:07 - main - ERROR - Failed in reading config file config.sample. Original message: readable_dir:/asfsadf is not a valid path
09/12/2015 12:44:37 - main - ERROR - Failed in reading config file config.sample. Original message: coercing to Unicode: need string or buffer, NoneType found
09/12/2015 12:46:11 - main - ERROR - Failed in reading config file config.sample. Original message: coercing to Unicode: need string or buffer, NoneType found
09/12/2015 12:46:31 - main - ERROR - Failed in reading config file config.sample. Original message: coercing to Unicode: need string or buffer, NoneType found
09/12/2015 12:46:31 - main - ERROR - Read the following config: <Config(debug='True', quiet='False', writable_path='None', no_parse='False', uri='.', extensions='', db_driver='mongo', db_user='root', db_password='root', db_database='smartshark', db_hostname='localhost', db_port='27017'
Traceback (most recent call last):
  File "/home/fabian/Arbeit/cvsSHARK/cvsSHARK/pycvsshark/__init__.py", line 75, in start
    config.load_from_file(args.config_file)
  File "/home/fabian/Arbeit/cvsSHARK/cvsSHARK/pycvsshark/config.py", line 81, in load_from_file
    raise ErrorLoadingConfig(config_file, e)
ErrorLoadingConfig: Failed in reading config file config.sample. Original message: coercing to Unicode: need string or buffer, NoneType found
09/12/2015 12:47:45 - main - ERROR - Failed in reading config file config.sample. Original message: coercing to Unicode: need string or buffer, NoneType found
09/12/2015 12:47:45 - main - ERROR - Read the following config: <Config(debug='True', quiet='False', writable_path='None', no_parse='False', uri='.', extensions='', db_driver='mongo', db_user='root', db_password='root', db_database='smartshark', db_hostname='localhost', db_port='27017'
Traceback (most recent call last):
  File "/home/fabian/Arbeit/cvsSHARK/cvsSHARK/pycvsshark/__init__.py", line 75, in start
    config.load_from_file(args.config_file)
  File "/home/fabian/Arbeit/cvsSHARK/cvsSHARK/pycvsshark/config.py", line 81, in load_from_file
    raise ErrorLoadingConfig(config_file, e)
ErrorLoadingConfig: Failed in reading config file config.sample. Original message: coercing to Unicode: need string or buffer, NoneType found
09/12/2015 13:23:41 - main - ERROR - Failed in reading config file config.sample. Original message: coercing to Unicode: need string or buffer, NoneType found
09/12/2015 13:23:41 - main - ERROR - Read the following config: <Config(debug='True', quiet='False', writable_path='bla', no_parse='False', uri='.', extensions='', db_driver='mongo', db_user='root', db_password='root', db_database='smartshark', db_hostname='localhost', db_port='27017'
Traceback (most recent call last):
  File "/home/fabian/Arbeit/cvsSHARK/cvsSHARK/pycvsshark/__init__.py", line 75, in start
    config.load_from_file(args.config_file)
  File "/home/fabian/Arbeit/cvsSHARK/cvsSHARK/pycvsshark/config.py", line 81, in load_from_file
    raise ErrorLoadingConfig(config_file, e)
ErrorLoadingConfig: Failed in reading config file config.sample. Original message: coercing to Unicode: need string or buffer, NoneType found
09/12/2015 13:25:26 - main - ERROR - Failed in reading config file config.sample. Original message: coercing to Unicode: need string or buffer, NoneType found
09/12/2015 13:25:26 - main - ERROR - Read the following config: bla
Traceback (most recent call last):
  File "/home/fabian/Arbeit/cvsSHARK/cvsSHARK/pycvsshark/__init__.py", line 75, in start
    config.load_from_file(args.config_file)
  File "/home/fabian/Arbeit/cvsSHARK/cvsSHARK/pycvsshark/config.py", line 81, in load_from_file
    raise ErrorLoadingConfig(config_file, e)
ErrorLoadingConfig: Failed in reading config file config.sample. Original message: coercing to Unicode: need string or buffer, NoneType found
09/12/2015 13:25:42 - main - ERROR - Failed in reading config file config.sample. Original message: coercing to Unicode: need string or buffer, NoneType found
09/12/2015 13:25:42 - main - ERROR - Read the following config: bla
Traceback (most recent call last):
  File "/home/fabian/Arbeit/cvsSHARK/cvsSHARK/pycvsshark/__init__.py", line 75, in start
    config.load_from_file(args.config_file)
  File "/home/fabian/Arbeit/cvsSHARK/cvsSHARK/pycvsshark/config.py", line 81, in load_from_file
    raise ErrorLoadingConfig(config_file, e)
ErrorLoadingConfig: Failed in reading config file config.sample. Original message: coercing to Unicode: need string or buffer, NoneType found
09/12/2015 13:26:04 - main - ERROR - Failed in reading config file config.sample. Original message: coercing to Unicode: need string or buffer, NoneType found
09/12/2015 13:26:04 - main - ERROR - Read the following config: bla
Traceback (most recent call last):
  File "/home/fabian/Arbeit/cvsSHARK/cvsSHARK/pycvsshark/__init__.py", line 75, in start
    config.load_from_file(args.config_file)
  File "/home/fabian/Arbeit/cvsSHARK/cvsSHARK/pycvsshark/config.py", line 82, in load_from_file
    raise ErrorLoadingConfig(config_file, e)
ErrorLoadingConfig: Failed in reading config file config.sample. Original message: coercing to Unicode: need string or buffer, NoneType found
09/12/2015 13:26:09 - main - ERROR - Failed in reading config file config.sample. Original message: coercing to Unicode: need string or buffer, NoneType found
09/12/2015 13:26:09 - main - ERROR - Read the following config: bla
Traceback (most recent call last):
  File "/home/fabian/Arbeit/cvsSHARK/cvsSHARK/pycvsshark/__init__.py", line 75, in start
    config.load_from_file(args.config_file)
  File "/home/fabian/Arbeit/cvsSHARK/cvsSHARK/pycvsshark/config.py", line 82, in load_from_file
    raise ErrorLoadingConfig(config_file, e)
ErrorLoadingConfig: Failed in reading config file config.sample. Original message: coercing to Unicode: need string or buffer, NoneType found
09/12/2015 13:26:17 - main - ERROR - Failed in reading config file config.sample. Original message: coercing to Unicode: need string or buffer, NoneType found
09/12/2015 13:26:17 - main - ERROR - Read the following config: bla
Traceback (most recent call last):
  File "/home/fabian/Arbeit/cvsSHARK/cvsSHARK/pycvsshark/__init__.py", line 75, in start
    config.load_from_file(args.config_file)
  File "/home/fabian/Arbeit/cvsSHARK/cvsSHARK/pycvsshark/config.py", line 83, in load_from_file
    raise ErrorLoadingConfig(config_file, e)
ErrorLoadingConfig: Failed in reading config file config.sample. Original message: coercing to Unicode: need string or buffer, NoneType found
09/12/2015 13:26:23 - main - ERROR - Failed in reading config file config.sample. Original message: coercing to Unicode: need string or buffer, NoneType found
09/12/2015 13:26:23 - main - ERROR - Read the following config: bla
Traceback (most recent call last):
  File "/home/fabian/Arbeit/cvsSHARK/cvsSHARK/pycvsshark/__init__.py", line 75, in start
    config.load_from_file(args.config_file)
  File "/home/fabian/Arbeit/cvsSHARK/cvsSHARK/pycvsshark/config.py", line 83, in load_from_file
    raise ErrorLoadingConfig(config_file, e)
ErrorLoadingConfig: Failed in reading config file config.sample. Original message: coercing to Unicode: need string or buffer, NoneType found
09/12/2015 13:26:30 - main - ERROR - Failed in reading config file config.sample. Original message: coercing to Unicode: need string or buffer, NoneType found
09/12/2015 13:26:30 - main - ERROR - Read the following config: bla
Traceback (most recent call last):
  File "/home/fabian/Arbeit/cvsSHARK/cvsSHARK/pycvsshark/__init__.py", line 75, in start
    config.load_from_file(args.config_file)
  File "/home/fabian/Arbeit/cvsSHARK/cvsSHARK/pycvsshark/config.py", line 83, in load_from_file
    raise ErrorLoadingConfig(config_file, e)
ErrorLoadingConfig: Failed in reading config file config.sample. Original message: coercing to Unicode: need string or buffer, NoneType found
09/12/2015 13:27:32 - main - ERROR - Read the following config: bla
None
09/12/2015 13:27:47 - main - ERROR - Read the following config: <Config(debug='True', quiet='False', writable_path='None', no_parse='False', uri='.', extensions='', db_driver='mongo', db_user='root', db_password='root', db_database='smartshark', db_hostname='localhost', db_port='27017'
None
09/12/2015 15:23:06 - main - ERROR - Failed to instantiate parser GitParser. Original message: Can't instantiate abstract class GitParser with abstract methods parse
09/12/2015 15:32:23 - main - ERROR - No fitting parser found for repository located at .
09/12/2015 15:52:31 - main - ERROR - No fitting parser found for repository located at .
09/12/2015 15:53:49 - main - ERROR - Failed in reading config file config.sample. Original message: readable_dir:/home/fabian/Arbeit/CVSAnaly is not a valid path
09/12/2015 15:53:49 - main - ERROR - Failed to instantiate parser GitParser. Original message: [Errno 2] No such file or directory: '/home/fabian/Arbeit/CVSAnaly'
09/12/2015 15:53:49 - main - ERROR - No fitting parser found for repository located at /home/fabian/Arbeit/CVSAnaly
09/12/2015 15:54:26 - main - ERROR - Failed in reading config file config.sample. Original message: readable_dir:/home/fabian/Arbeit/CVSAnaly is not a valid path
09/12/2015 15:54:43 - main - ERROR - No fitting parser found for repository located at /home/fabian/Arbeit/CVSAnalY
10/12/2015 09:41:19 - main - ERROR - Failed in reading config file config.sample. Original message: name 'ConfigParser' is not defined
10/12/2015 10:03:21 - main - ERROR - Failed to instantiate parser GitParser. Original message: '/home/fabian/Arbeit'
10/12/2015 10:03:21 - main - ERROR - No fitting parser found for repository located at /home/fabian/Arbeit
10/12/2015 10:04:10 - main - ERROR - Failed to instantiate parser GitParser. Original message: '/home/fabian/Arbeit'
10/12/2015 10:04:10 - main - ERROR - No fitting parser found for repository located at /home/fabian/Arbeit
10/12/2015 10:05:10 - main - ERROR - Failed to instantiate parser GitParser. Original message: name 'e' is not defined
10/12/2015 10:05:10 - main - ERROR - No fitting parser found for repository located at /home/fabian/Arbeit
10/12/2015 10:05:27 - main - ERROR - Failed to instantiate parser GitParser. Original message: '/home/fabian/Arbeit'
10/12/2015 10:05:27 - main - ERROR - No fitting parser found for repository located at /home/fabian/Arbeit
10/12/2015 10:05:39 - main - ERROR - Failed to instantiate parser GitParser. Original message: '/home/fabian'
10/12/2015 10:05:39 - main - ERROR - No fitting parser found for repository located at /home/fabian
10/12/2015 10:06:25 - main - ERROR - No fitting parser found for repository located at /home/fabian
10/12/2015 10:10:16 - main - ERROR - No fitting parser found for repository located at /home/fabian
17/12/2015 11:19:16 - main - ERROR - Failed to instantiate parser BlaStore. Original message: Can't instantiate abstract class BlaStore with abstract methods addCommit, storeIdentifier
17/12/2015 11:19:36 - main - ERROR - Failed to instantiate parser BlaStore. Original message: Can't instantiate abstract class BlaStore with abstract methods addCommit, storeIdentifier
17/12/2015 11:37:04 - main - ERROR - No datastores found! Exiting...
17/12/2015 11:38:52 - main - ERROR - Failed to instantiate datastore. Original message: Can't instantiate abstract class BlaStore with abstract methods addCommit, deleteAll
17/12/2015 11:50:16 - main - ERROR - Failed to instantiate parser. Original message: Can't instantiate abstract class SVNParser with abstract methods parse
17/12/2015 11:50:39 - main - ERROR - Failed to instantiate parser. Original message: name 'self' is not defined
17/12/2015 11:51:28 - main - ERROR - Failed to instantiate parser. Original message: name 'self' is not defined
17/12/2015 11:51:59 - main - ERROR - Failed to instantiate parser. Original message: name 'self' is not defined
17/12/2015 11:52:33 - main - ERROR - Failed to instantiate parser. Original message: findCorrectParser() missing 1 required positional argument: 'repositoryPath'
17/12/2015 15:59:02 - main - ERROR - Failed to instantiate parser. Original message: name 'logging' is not defined
17/12/2015 16:02:40 - main - ERROR - Failed to instantiate parser. Original message: name 'parser' is not defined
17/12/2015 16:03:04 - main - ERROR - Failed to instantiate parser. Original message: name 'parser' is not defined
17/12/2015 16:03:44 - main - ERROR - Failed to instantiate parser. Original message: name 'logging' is not defined
17/12/2015 16:05:08 - main - ERROR - Failed to instantiate parser. Original message: name 'logging' is not defined
17/12/2015 16:06:26 - main - ERROR - Failed to instantiate parser. Original message: name 'logging' is not defined
17/12/2015 17:14:18 - main - ERROR - Failed to instantiate parser. Original message: name 'queue' is not defined
17/12/2015 17:14:26 - main - ERROR - Failed to instantiate parser. Original message: name 'queue' is not defined
18/12/2015 14:56:58 - main - ERROR - Failed to instantiate parser. Original message: unexpected indent (gitparser.py, line 88)
18/12/2015 15:38:54 - main - ERROR - Failed to instantiate parser. Original message: positional argument follows keyword argument (gitparser.py, line 257)
18/12/2015 15:47:17 - main - ERROR - Failed to instantiate datastore. Original message: No module named 'mongoengine'
18/12/2015 15:48:22 - main - ERROR - Failed to instantiate datastore. Original message: name 'ListField' is not defined
18/12/2015 16:45:33 - main - ERROR - Failed to instantiate datastore. Original message: expected an indented block (mongostore.py, line 40)
18/12/2015 16:45:50 - main - ERROR - Failed to instantiate parser. Original message: name 'CommitModel' is not defined
18/12/2015 16:47:01 - main - ERROR - Failed to instantiate parser. Original message: name 'CommitModel' is not defined
18/12/2015 16:48:00 - main - ERROR - Failed to instantiate parser. Original message: name 'CommitModel' is not defined
18/12/2015 16:51:04 - main - ERROR - Failed to instantiate parser. Original message: name 'branches' is not defined
18/12/2015 16:54:18 - main - ERROR - Failed to instantiate parser. Original message: name 'tags' is not defined
21/12/2015 09:45:05 - main - ERROR - Failed to instantiate datastore. Original message: name 'logging' is not defined
21/12/2015 09:45:20 - main - ERROR - Failed to instantiate datastore. Original message: name 'abc' is not defined
21/12/2015 09:45:31 - main - ERROR - Failed to instantiate datastore. Original message: name 'abc' is not defined
21/12/2015 10:15:11 - main - ERROR - Failed to instantiate parser. Original message: No fitting parser found for repository located at /home/fabian/Arbeit/vcsSHARK/vcsSHARK
21/12/2015 10:15:18 - main - ERROR - Failed to instantiate parser. Original message: No fitting parser found for repository located at /home/fabian/Arbeit/vcsSHARK/vcsSHARK
21/12/2015 10:16:27 - main - ERROR - Failed to instantiate datastore. Original message: No module named 'mongoengine'
21/12/2015 10:42:29 - main - ERROR - Failed to instantiate datastore. Original message: name 'IntField' is not defined
21/12/2015 10:49:35 - main - ERROR - Failed to instantiate parser. Original message: name 'tagger' is not defined
22/12/2015 11:59:58 - main - ERROR - Failed to instantiate datastore. Original message: name 'StringField' is not defined
22/12/2015 14:11:12 - main - ERROR - Failed to instantiate datastore. Original message: Cannot resolve field "commitId"
22/12/2015 16:44:18 - main - ERROR - Failed to instantiate datastore. Original message: expected an indented block (mongostore.py, line 62)
23/12/2015 09:51:12 - main - ERROR - Failed to instantiate datastore. Original message: No module named 'Queue'
23/12/2015 10:36:24 - main - ERROR - Failed to instantiate datastore. Original message: invalid syntax (mongostore.py, line 148)
23/12/2015 11:43:06 - main - ERROR - Failed to instantiate datastore. Original message: invalid syntax (mongostore.py, line 7)
23/12/2015 11:43:57 - main - ERROR - Failed to instantiate datastore. Original message: No module named 'pymongo.objectid'
23/12/2015 11:45:32 - main - ERROR - Failed to instantiate datastore. Original message: cannot import name 'ObjectId'
